# Generated by Django 4.1.7 on 2024-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraTrack', '0002_remove_user_id_alter_user_register_no_rentalbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
