# Generated by Django 4.1.7 on 2024-02-19 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraTrack', '0003_book_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField(default=datetime.datetime.now)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraTrack.book')),
                ('register_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_register', to='LibraTrack.user')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_student', to='LibraTrack.user')),
            ],
        ),
    ]
