# Generated by Django 4.1.7 on 2024-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraTrack', '0004_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalbook',
            old_name='book',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='rentalbook',
            old_name='user',
            new_name='register_no',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
