# Generated by Django 4.1.7 on 2024-02-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraTrack', '0005_rename_book_rentalbook_book_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_name',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
