# Generated by Django 4.1.7 on 2024-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraTrack', '0006_user_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
